### ISSUE TITLE
Compile error in the examples with OpenCV 4.0.0-alpha

### ISSUE THREAD

**Issue by Dovyski** [Dovyski/cvui#52]
Some examples do not compile using OpenCV 4.0.0-alpha. The error:

```
home/travis/build/Dovyski/cvui/example/src/canny/main.cpp: In function ‘int main(int, const char**)’:
/home/travis/build/Dovyski/cvui/example/src/canny/main.cpp:29:30: error: ‘CV_BGR2GRAY’ was not declared in this scope
    cv::cvtColor(lena, frame, CV_BGR2GRAY);
                              ^
/home/travis/build/Dovyski/cvui/example/src/canny/main.cpp:31:31: error: ‘CV_GRAY2BGR’ was not declared in this scope
    cv::cvtColor(frame, frame, CV_GRAY2BGR);
```

It seems `CV_BGR2GRAY` should be replaced with `cv::COLOR_BGR2GRAY`.
